### PR TITLE
update goreleaser workflow to use new token

### PR DESCRIPTION
**Pull request by svix-frank**

### CODE REVIEW

**Review by tasn — COMMENTED** [review]
I'm still unsure whether it'll work. The problem is that this token doesn't have write access to this repository (that we are currently on)...

Have you tested it?

**Comment by svix-frank** [comment]
> I'm still unsure whether it'll work. The problem is that this token doesn't have write access to this repository (that we are currently on)...
> 
> Have you tested it?

It will need access to all 3 repos

**Comment by tasn** [comment]
I knew this was coming... Do people actually give such wide-net access to tools? Am I the only crazy one that don't give everything and everyone permissions all the time? :(

**Review by tasn — APPROVED** [review]
I gave it access to this repo too. But just FYI, I'm sad. :P

**Pull request merged**
