### PR TITLE
enable color by default if stdout is a TTY

### LINKED ISSUE #7: Automatically enable `--color` if in a TTY
There's a way to detect whether we are in a TTY or a script. If we are in a TTY we should have color on by default. It's just too good to not have on. :)

### PR DESCRIPTION
**Pull request by svix-frank**
Closes #7.

### CODE REVIEW

**Review by tasn — APPROVED** [review]
I don't know golang, though I guess it's fine? Assuming this works on linux, macos and windows?
Is it possible to disable it? `--no-color` or something when it's on?

**Comment by svix-frank** [comment]
> I don't know golang, though I guess it's fine? Assuming this works on linux, macos and windows?
> Is it possible to disable it? `--no-color` or something when it's on?

Yeah it works on all platforms.
Currently you can pass `--color=false` to disable, although a `--no-color` flag might be clear.

**Comment by tasn** [comment]
--color=false actually sounds better! Maybe do that?

**Comment by svix-frank** [comment]
> --color=false actually sounds better! Maybe do that?

Okay, reverted!

**Pull request merged**
